### ISSUE TITLE
Broken windows build re-enable

### ISSUE THREAD

**Issue by redgold-labs** [redgold-io/redgold#428]
Windows build broke due to some external change.

The following warnings were emitted during compilation:

warning: gcc.exe: warning: /std:c11: linker input file unused because linking not done
warning: gcc.exe: error: /std:c11: linker input file not found: No such file or directory

error: failed to run custom build command for `c-kzg v0.1.1`

Caused by:
  process didn't exit successfully: `D:\a\redgold\redgold\target\release\build\c-kzg-834b9980e88d8be5\build-script-build` (exit code: 101)
  --- stdout
  TARGET = Some("x86_64-pc-windows-gnu")
  OPT_LEVEL = Some("1")
  HOST = Some("x86_64-pc-windows-gnu")
  cargo:rerun-if-env-changed=CC_x86_64-pc-windows-gnu
  CC_x86_64-pc-windows-gnu = None
  cargo:rerun-if-env-changed=CC_x86_64_pc_windows_gnu
  CC_x86_64_pc_windows_gnu = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  cargo:rerun-if-env-changed=CFLAGS_x86_64-pc-windows-gnu
  CFLAGS_x86_64-pc-windows-gnu = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64_pc_windows_gnu
  CFLAGS_x86_64_pc_windows_gnu = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  running: "gcc.exe" "-O1" "-ffunction-sections" "-fdata-sections" "-m64" "-I" "C:\\Users\\runneradmin\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\c-kzg-0.1.1\\c-kzg-sys\\blst\\bindings" "-D_CRT_SECURE_NO_WARNINGS" "/std:c11" "-DLIB_PREFIX=ckzg" "-DFIELD_ELEMENTS_PER_BLOB=4096" "-o" "D:\\a\\redgold\\redgold\\target\\x86_64-pc-windows-gnu\\release\\build\\c-kzg-74d4b4805e1e6964\\out\\c08e3e867c0ecc26-c_kzg_4844.o" "-c" "C:\\Users\\runneradmin\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\c-kzg-0.1.1\\c-kzg-sys\\src\\c_kzg_4844.c"
  cargo:warning=gcc.exe: warning: /std:c11: linker input file unused because linking not done

  cargo:warning=gcc.exe: error: /std:c11: linker input file not found: No such file or directory

  exit code: 1

  --- stderr
  Using LIB_PREFIX=ckzg
  Using FIELD_ELEMENTS_PER_BLOB=4096
  thread 'main' panicked at 'Failed to compile ckzg: Error { kind: ToolExecError, message: "Command \"gcc.exe\" \"-O1\" \"-ffunction-sections\" \"-fdata-sections\" \"-m64\" \"-I\" \"C:\\\\Users\\\\runneradmin\\\\.cargo\\\\registry\\\\src\\\\index.crates.io-6f17d22bba15001f\\\\c-kzg-0.1.1\\\\c-kzg-sys\\\\blst\\\\bindings\" \"-D_CRT_SECURE_NO_WARNINGS\" \"/std:c11\" \"-DLIB_PREFIX=ckzg\" \"-DFIELD_ELEMENTS_PER_BLOB=4096\" \"-o\" \"D:\\\\a\\\\redgold\\\\redgold\\\\target\\\\x86_64-pc-windows-gnu\\\\release\\\\build\\\\c-kzg-74d4b4805e1e6964\\\\out\\\\c08e3e867c0ecc26-c_kzg_4844.o\" \"-c\" \"C:\\\\Users\\\\runneradmin\\\\.cargo\\\\registry\\\\src\\\\index.crates.io-6f17d22bba15001f\\\\c-kzg-0.1.1\\\\c-kzg-sys\\\\src\\\\c_kzg_4844.c\" with args \"gcc.exe\" did not execute successfully (status code exit code: 1)." }', C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\c-kzg-0.1.1\build.rs:52:30
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
Error: Process completed with exit code 101.

  build-windows:
    #    needs: [test]
    if:
      contains('
      refs/heads/predev
      refs/heads/dev
      refs/heads/staging
      refs/heads/test
      refs/heads/main
      ', github.ref)
    runs-on: windows-2019
    timeout-minutes: 100
    permissions:
      contents: write
    env:
      DATABASE_URL: "sqlite:///Users/runner/work/redgold-core/redgold-core/.rg/sqlx/data_store.sqlite"
    outputs:
      release_match: ${{ steps.check-branch.outputs.match }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.TOOLCHAIN }}
          target: x86_64-pc-windows-gnu
          default: true
          override: true
      - uses: msys2/setup-msys2@v2
      - run: echo "asdf" > ./redgold.exe
      - shell: msys2 {0}
        name: "Msys2 cargo build with dependencies"
        if:
          contains('
          refs/heads/staging
          refs/heads/test
          refs/heads/main
          ', github.ref)
        run: |
          export PATH="$HOME/.cargo/bin:$PATH"
          uname -a
          ls -lA
          pwd
          pacman -S --noconfirm mingw-w64-x86_64-gmp
          pacman -S --noconfirm mingw-w64-x86_64-rust
          pacman -S --noconfirm mingw-w64-x86_64-openssl
          pacman -S --noconfirm make 
          echo "OPENSSL_DIR=/mingw64" >> $GITHUB_ENV
          echo "OPENSSL_STATIC=yes" >> $GITHUB_ENV
          cargo build --release --target x86_64-pc-windows-gnu
          ls 
          ls target/
          ls target/x86_64-pc-windows-gnu/
          ls target/x86_64-pc-windows-gnu/release/
          cp target/x86_64-pc-windows-gnu/release/redgold.exe ./redgold.exe
      - uses: actions/upload-artifact@v3
        with:
          name: redgold.exe
          path: ./redgold.exe

ChatGPT

The primary issue you're facing is that the gcc compiler is being passed a /std:c11 flag, which is not a valid flag for gcc. This flag is typically used with Microsoft's cl compiler.

To address this:

    Check the build.rs of the c-kzg crate you are compiling. It seems that /std:c11 is being passed as a compiler flag. It may need to be changed or removed.
    If c-kzg crate is a third-party crate and you don't have control over its build.rs, you might need to either:
        Report an issue to the maintainers of the crate, asking for better Windows support.
        Fork the crate and modify it to suit your needs.

Considering your GitHub Actions script, it seems you are using a mixture of native Windows tools and MSYS2. Be careful with this as mixing these environments can cause issues. You might need to ensure that you're using the right gcc (from MSYS2, not any native Windows one).

Here's a possible action plan:

    Ensure you're using the right gcc.
        After setting up MSYS2, add its bin directory to the PATH. For example, add:

        yaml

        echo "/mingw64/bin:$PATH" >> $GITHUB_ENV

        after your pacman commands.
    Modify or ensure the build scripts of the crate don't include flags incompatible with gcc.
    If you're overriding the compiler or providing flags globally, ensure they're compatible with the crates you're building.

Lastly, ensure that you've set the TOOLCHAIN environment variable, as it's being used in the GitHub Actions but isn't defined in the provided snippet.

**Comment by sergei-pq** [comment]
https://github.com/redgold-io/redgold/tree/win-test
